---
language: python
python: "2.7"

install:
# Install Ansible
- pip install ansible

# Edit ansible.cfg to pick up roles path.
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
# Check test playbook syntax
- "ansible-playbook -i tests/inventory tests/provision.yml --syntax-check"

# Run the test playbook
- "ansible-playbook -i tests/inventory tests/provision.yml --connection=local --sudo"

# Run the test playbook again to test it idempotent
- >
  ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)

# Test Composer is installed
#- >
#  wp cli version
#  | grep -q 'WP-CLI'
#  && (echo 'WP-CLI install successful' && exit 0)
#  || (echo 'WP-CLI install failed' && exit 1)